### PR TITLE
Let the backend and frontend communicate with each other about in-person purchase

### PR DESCRIPTION
**Pull request by mutokrm**
## Demo
- Sellers can set password for in-person purchase
- They can see the password if it's available for in-person purchase
- They cannot see password for other's items

https://github.com/xu-jiach/mercari-build-hackathon-2023/assets/90857923/3a493599-a659-4baa-867e-c91a9cdc78f1

## TODO
- Enable the edit item `PUT /items/:itemID` endpoint for item password

### CODE REVIEW

**Comment by noliver-ykc** [comment]
Hi! Sorry if I missed it, but were you able to implement the actual buying process? (so actually testing if putting in the right code gets it marked as sold)

**Comment by mutokrm** [comment]
@noliver-ykc not yet! I'm working on it on another branch! I'll get it done tomorrow morning!

**Comment by noliver-ykc** [comment]
> @noliver-ykc not yet! I'm working on it on another branch! I'll get it done tomorrow morning!

Great, がんば！

**Review by noliver-ykc — COMMENTED** [review]
LGTM

**Pull request merged**
