### PR TITLE
Add item form ui has been updated

### PR DESCRIPTION
**Pull request by noliver-ykc**
I also changed the display order of items in your profile, mpst recent items not appear at the top.

https://github.com/xu-jiach/mercari-build-hackathon-2023/assets/74501096/520ae67d-0996-4f2a-a67d-34bf5acacd56

### CODE REVIEW

**Comment by xu-jiach** [comment]
For the item list, do you think having grid with multiple items in a row will look better? I just generally feel that's better since we are on a webpage instead of mobile.

**Comment by noliver-ykc** [comment]
> For the item list, do you think having grid with multiple items in a row will look better? I just generally feel that's better since we are on a webpage instead of mobile.

Most forms are pretty common to have things line up in a single row. 
usually things will be multiple rows for things like first name last name or other very closely related things. so i think its fine like this


here is mercari's web version, as you can see its one column

https://github.com/xu-jiach/mercari-build-hackathon-2023/assets/74501096/eb8e4cf4-199f-4356-9688-31fac26daa1c

**Comment by xu-jiach** [comment]
> > For the item list, do you think having grid with multiple items in a row will look better? I just generally feel that's better since we are on a webpage instead of mobile.
> 
> Most forms are pretty common to have things line up in a single row. usually things will be multiple rows for things like first name last name or other very closely related things. so i think its fine like this
> 
> here is mercari's web version, as you can see its one column
> Screen.Recording.2023-05-28.at.0.09.58.mov

I like that part. I think it's clear and nice. Maybe nicer if stretching the box and make it wider will even better.
What I am saying is the user page, which I think might be nicer with the smaller pic but more items in each row.
Eventually, this page is implemented as a summary for individual users so more information might be better?
图片

**Comment by noliver-ykc** [comment]
> > > For the item list, do you think having grid with multiple items in a row will look better? I just generally feel that's better since we are on a webpage instead of mobile.
> > 
> > 
> > Most forms are pretty common to have things line up in a single row. usually things will be multiple rows for things like first name last name or other very closely related things. so i think its fine like this
> > here is mercari's web version, as you can see its one column
> > Screen.Recording.2023-05-28.at.0.09.58.mov
> 
> I like that part. I think it's clear and nice. Maybe nicer if stretching the box and make it wider will even better. What I am saying is the user page, which I think might be nicer with the smaller pic but more items in each row. Eventually, this page is implemented as a summary for individual users so more information might be better? 图片

The form is now a little bigger! For the my page, i didnt edit any of the ui for that just made the new items at the top. Kurumi's recent PR has to do with adding multiple rows of images for the listing so it might already be implemented over there. Otherwise we can probably adapt the code so it works on both sections later on!


Screenshot 2023-05-28 at 0 20 21

**Comment by xu-jiach** [comment]
> > > > For the item list, do you think having grid with multiple items in a row will look better? I just generally feel that's better since we are on a webpage instead of mobile.
> > > 
> > > 
> > > Most forms are pretty common to have things line up in a single row. usually things will be multiple rows for things like first name last name or other very closely related things. so i think its fine like this
> > > here is mercari's web version, as you can see its one column
> > > Screen.Recording.2023-05-28.at.0.09.58.mov
> > 
> > 
> > I like that part. I think it's clear and nice. Maybe nicer if stretching the box and make it wider will even better. What I am saying is the user page, which I think might be nicer with the smaller pic but more items in each row. Eventually, this page is implemented as a summary for individual users so more information might be better? 图片
> 
> The form is now a little bigger! For the my page, i didnt edit any of the ui for that just made the new items at the top. Kurumi's recent PR has to do with adding multiple rows of images for the listing so it might already be implemented over there. Otherwise we can probably adapt the code so it works on both sections later on!
> Screenshot 2023-05-28 at 0 20 21

This looks really nice!

**Pull request merged**
